# base is generated by ChatGPT and adapted 

import requests
import re

# Define a list of URLs to check
urls = [
    "https://www.website1.com/prices",
    "https://www.website2.com/prices",
    "https://www.website3.com/prices",
    "https://www.website4.com/prices",
    "https://www.website5.com/prices",
    "https://www.website6.com/prices",
    "https://www.website7.com/prices",
    "https://www.website8.com/prices",
    "https://www.website9.com/prices",
    "https://www.website10.com/prices"
]

def parse_price_from_html(html):
    # Use a regular expression to search for a price in the HTML
    price_pattern = r"\$\d+\.\d+"
    match = re.search(price_pattern, html)

    # If a match is found, return the price
    if match:
        return match.group()
    else:
        # If no match is found, return None
        return None

# Loop through the list of URLs
for url in urls:
    # Send a GET request to each URL
    response = requests.get(url)

    # Check the response status code
    if response.status_code == 200:
        # If the response is successful, parse the price from the website's HTML
        # and print it out
        price = parse_price_from_html(response.text)
        print(f"The price on {url} is {price}")
    else:
        # If the response is not successful, print an error message
        print(f"Unable to get price from {url}: {response.status_code}")

